# GitHub Action for generating a contribution graph with a snake eating the contributions
name: Generate Snake Animation

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # ⭐️⭐️⭐️ THIS IS THE MOST LIKELY FIX ⭐️⭐️⭐️
    # This grants the workflow permission to write to the repository.
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: ${{ github.repository_owner }}

          # The output file paths
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # The branch to push the generated files to
          target_branch: output
          # The directory to publish
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
